
const data = [{
    make: "Tesla",
    model: "Model S",
    type: "car coupe electric",
    color: "red",
    year: 2021,
    miles: 65000,
    price: 45000,
    transmission: "automatic",
    used: true,
    id: 1,
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/2018_Tesla_Model_S_75D.jpg/1200px-2018_Tesla_Model_S_75D.jpg",
  },
  {
    make: "Toyota",
    model: "Camry",
    type: "car sedan",
    color: "silver gray grey",
    year: 2018,
    miles: 85000,
    price: 18000,
    transmission: "automatic",
    used: true,
    id: 2,
    url: "https://media.ed.edmunds-media.com/toyota/camry-hybrid/2021/oem/2021_toyota_camry-hybrid_sedan_xse_fq_oem_1_1600.jpg",
  },
  {
    make: "Ford",
    model: "Focus",
    type: "car sedan",
    color: "silver gray grey",
    year: 2012,
    miles: 65000,
    price: 15000,
    transmission: "automatic",
    used: true,
    id: 3,
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/2008_Ford_Focus_Zetec_TD_109_1.6_Front.jpg/1200px-2008_Ford_Focus_Zetec_TD_109_1.6_Front.jpg",
  },
  {
    make: "Tesla",
    model: "Cybertruck",
    type: "truck electric",
    color: "silver metallic chrome gray grey",
    year: 2022,
    miles: 0,
    price: 69900,
    transmission: "automatic",
    used: false,
    owners: "new",
    id: 4,
    url: "https://hips.hearstapps.com/hmg-prod/images/2022-tesla-cyber-truck-mmp-1-1579127142.jpg?crop=0.788xw:1.00xh;0.107xw,0&resize=640:*",
  },
  {
    make: "Toyota",
    model: "Corolla",
    type: "car sedan",
    color: "silver gray grey",
    year: 2013,
    miles: 96000,
    price: 10000,
    transmission: "automatic",
    used: true,
    id: 5,
    url: "https://bloximages.newyork1.vip.townnews.com/richmond.com/content/tncms/assets/v3/classifieds/b/16/b167bc45-cbb7-56ec-b121-027bf9243ac6/5ec9f3164513c.image.jpg",
  },
  {
    make: "Honda",
    model: "Civic",
    type: "car coupe",
    color: "white",
    year: 2015,
    miles: 120000,
    price: 14000,
    transmission: "automatic",
    used: true,
    id: 6,
    url: "https://i.ytimg.com/vi/zt8L0aV2ZjM/maxresdefault.jpg",
  },
  {
    make: "Ford",
    model: "Ranger",
    type: "truck",
    year: 2008,
    color: "blue",
    miles: 165000,
    price: 7499,
    transmission: "manual",
    used: true,
    id: 7,
    url: "",
  },
  {
    make: "Honda",
    model: "Accord",
    type: "car sedan",
    color: "white",
    year: 2017,
    miles: 86800,
    price: 15500,
    transmission: "automatic",
    used: true,
    id: 8,
    url: "https://upload.wikimedia.org/wikipedia/commons/2/27/Honda_Accord_%28CV3%29_EX_eHEV%2C_2021%2C_front.jpg",
  },
  {
    make: "Nissan",
    model: "Altima",
    type: "car sedan",
    color: "blue",
    year: 2015,
    miles: 55000,
    price: 14500,
    transmission: "manual",
    used: true,
    id: 9,
    url: "https://cdn.motor1.com/images/mgl/jqn77/s1/2021-nissan-altima.jpg",
  },
  {
    make: "Toyota",
    model: "Tacoma",
    type: "truck",
    color: "red",
    year: 2011,
    miles: 255000,
    price: 6500,
    transmission: "manual",
    used: true,
    id: 10,
    url: "https://automanager.blob.core.windows.net/wmphotos/019736/2a0980d863221849b0bde4e3e301b180/aa1878c246_640.jpg",
  },
  {
    make: "toyota",
    model: "camry",
    type: "car sedan",
    color: "black",
    year: "2020",
    miles: "55000",
    price: "16000",
    transmission: "automatic",
    used: true,
    id: 11,
    url: "https://i.ytimg.com/vi/lwlut1Ym0q8/maxresdefault.jpg",
  },
  {
    make:'chevrolet',
    type:'car sedan',
    model:'el camino',
    color:'black',
    year:'1981',
    miles:'81000',
    price:'15999',
    transmission:'automatic',
    used:'true',
    id:12,
    url:'https://silodrome.com/wp-content/uploads/2020/11/Chevrolet-El-Camino-SS_-14.jpg'
  },
]

export default data

//hasura ^^^